# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d5931e6cde935e6ae9780a2b62e7756a0219249dbc77d899ced3202dee0948a796fc4e1f3ab348f7c91ec4e8264d98303ec1c0d2141c7accf5339da431b75a05

test:
  secret_key_base: 4126bcfff133882d1a2e65897e29715386c8e22af52cc51a01a390a3c1ce5ac2fc80ce33fbb025ea2c0917652d83a05c4c23fec207d98e4226ecbc3c73dc48ed

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
